temporary disabling rancher wf for troubleshooting

diff --git a/.github/workflows/master_rancher_ui_workflow.yml b/.github/workflows/master_rancher_ui_workflow.yml
--- a/.github/workflows/master_rancher_ui_workflow.yml
+++ b/.github/workflows/master_rancher_ui_workflow.yml
@@ -252,77 +252,77 @@ jobs:
           path: mochawesome-report
           retention-days: 7
 
-  cypress-epinio-uninstall:
-    needs:
-      - installation
-      - cypress-epinio-installation
-      - epinio-patching
-      - cypress-epinio-tests
-    runs-on: ${{ inputs.runner }}
-    container:
-      image: ${{ inputs.cypress_image }}
-      env:
-        CLUSTER_NAME: local
-        RANCHER_USER: admin
-        RANCHER_PASSWORD: rancherpassword
-        RANCHER_URL: https://${{ needs.installation.outputs.MY_HOSTNAME }}/dashboard
-        SYSTEM_DOMAIN: ${{ needs.installation.outputs.MY_IP }}.omg.howdoi.website
-        UI: rancher
-      options: --add-host ${{ needs.installation.outputs.MY_HOSTNAME }}:${{ needs.installation.outputs.MY_IP }} --ipc=host ${{ inputs.docker_options }}
-    steps:
+  # cypress-epinio-uninstall:
+  #   needs:
+  #     - installation
+  #     - cypress-epinio-installation
+  #     - epinio-patching
+  #     - cypress-epinio-tests
+  #   runs-on: ${{ inputs.runner }}
+  #   container:
+  #     image: ${{ inputs.cypress_image }}
+  #     env:
+  #       CLUSTER_NAME: local
+  #       RANCHER_USER: admin
+  #       RANCHER_PASSWORD: rancherpassword
+  #       RANCHER_URL: https://${{ needs.installation.outputs.MY_HOSTNAME }}/dashboard
+  #       SYSTEM_DOMAIN: ${{ needs.installation.outputs.MY_IP }}.omg.howdoi.website
+  #       UI: rancher
+  #     options: --add-host ${{ needs.installation.outputs.MY_HOSTNAME }}:${{ needs.installation.outputs.MY_IP }} --ipc=host ${{ inputs.docker_options }}
+  #   steps:
 
-      - name: Cypress run
-        uses: cypress-io/github-action@v5
-        with:
-          browser: ${{ inputs.browser }}
-          # headless: true
-          spec: |
-            cypress/e2e/unit_tests/uninstall.spec.ts
-          config-file: cypress.config.ts
+  #     - name: Cypress run
+  #       uses: cypress-io/github-action@v5
+  #       with:
+  #         browser: ${{ inputs.browser }}
+  #         # headless: true
+  #         spec: |
+  #           cypress/e2e/unit_tests/uninstall.spec.ts
+  #         config-file: cypress.config.ts
 
-      - name: Copying screenshots and videos to Mochawesome report
-        if: always()
-        run: |
-          mkdir -p mochawesome-report
-          cp -r cypress/screenshots mochawesome-report || echo "No screenshots found in this run, probably all tests were OK"     
-          cp -r cypress/videos mochawesome-report
+  #     - name: Copying screenshots and videos to Mochawesome report
+  #       if: always()
+  #       run: |
+  #         mkdir -p mochawesome-report
+  #         cp -r cypress/screenshots mochawesome-report || echo "No screenshots found in this run, probably all tests were OK"     
+  #         cp -r cypress/videos mochawesome-report
 
-      - name: Upload Cypress screenshots
-        uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: cypress-screenshots-uninstall
-          path: cypress/screenshots
-          retention-days: 7
+  #     - name: Upload Cypress screenshots
+  #       uses: actions/upload-artifact@v3
+  #       if: failure()
+  #       with:
+  #         name: cypress-screenshots-uninstall
+  #         path: cypress/screenshots
+  #         retention-days: 7
 
-      # Test run video was always captured, so this action uses "always()" condition
-      - name: Upload Cypress videos
-        uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: cypress-videos-uninstall
-          path: cypress/videos
-          retention-days: 7
+  #     # Test run video was always captured, so this action uses "always()" condition
+  #     - name: Upload Cypress videos
+  #       uses: actions/upload-artifact@v3
+  #       if: always()
+  #       with:
+  #         name: cypress-videos-uninstall
+  #         path: cypress/videos
+  #         retention-days: 7
 
-      - name: Upload Mochawesome report
-        uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: mochawesome-report
-          path: mochawesome-report
-          retention-days: 7
+  #     - name: Upload Mochawesome report
+  #       uses: actions/upload-artifact@v3
+  #       if: always()
+  #       with:
+  #         name: mochawesome-report
+  #         path: mochawesome-report
+  #         retention-days: 7
 
-  delete-cluster:
-    if: always()
-    needs: [installation, cypress-epinio-installation, epinio-patching, cypress-epinio-tests, cypress-epinio-uninstall]
-    runs-on: ${{ inputs.runner }}
-    steps:
+  # delete-cluster:
+  #   if: always()
+  #   needs: [installation, cypress-epinio-installation, epinio-patching, cypress-epinio-tests, cypress-epinio-uninstall]
+  #   runs-on: ${{ inputs.runner }}
+  #   steps:
 
-      - name: Delete k3s cluster
-        if: always()
-        run: |
-          make clean-all
+  #     - name: Delete k3s cluster
+  #       if: always()
+  #       run: |
+  #         make clean-all
 
-      - name: Clean all
-        if: always()
-        uses: colpal/actions-clean@v1
+  #     - name: Clean all
+  #       if: always()
+  #       uses: colpal/actions-clean@v1
